### ISSUE TITLE
Configuration is all empty strings?

### ISSUE THREAD

**Issue by BlueAmulet** [taffyko/LCNiceChat#3]
Was wondering why all of the configuration entries are of type String and default to an empty string. You can make config entries of different types. You also wouldn't have to bother with TryParse as the config system automatically does that anyway.

Instead of
```
if (float.TryParse(
            Config.Bind<string?>("Chat", "DefaultFontSize", null, "(default: 11) The base game's font size is 13").Value,
            out var _defaultFontSize
        )) { defaultFontSize = _defaultFontSize; };
```

you could just do
```
defaultFontSize = Config.Bind("Chat", "DefaultFontSize", defaultFontSize, "The base game's font size is 13").Value;
```

**Comment by taffyko** [comment]
hi there! the reason i did this is because it allows me to change default settings in a future update and have them retroactively apply to any players that didn't customize those settings.
— if i use BepInEx's default value option (which writes the default values to the config file), it becomes ambiguous whether the user set the values explicitly or simply never touched them and left them at their defaults.

the majority of users don't edit the config files — and i want to make sure i can change the defaults down the line in case they end up being badly chosen in hindsight, without having to actually modify anyone's config files to do so.

(unfortunately, the BepInEx config API doesn't support nullable value types, so i had to make them all strings so that i could use null/empty to mean "default")

**Comment by BlueAmulet** [comment]
Makes sense
